
# safelist
branches:
  only:
  - master

language: cpp
compiler: gcc
os:
  - linux
  - osx


before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then mkdir $HOME/usr && export PATH="$HOME/usr/bin:$PATH" && wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh && chmod +x cmake-3.7.2-Linux-x86_64.sh && ./cmake-3.7.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license; fi
install: mkdir build && cd build && rm -fR * && cmake ..

before_script:

script: make