<<<<<<< HEAD

# safelist
branches:
  only:
  - master

language: cpp
compiler: gcc
os:
  - linux
  - osx


before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then mkdir $HOME/usr && export PATH="$HOME/usr/bin:$PATH" && wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh && chmod +x cmake-3.7.2-Linux-x86_64.sh && ./cmake-3.7.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license; fi
install: mkdir build && cd build && rm -fR * && cmake ..

before_script:

script: make
=======
sudo: required
language: generic

matrix:
  include:
# Makefile builder
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: BUILDER=make DISTRO=native LANGUAGE=cc
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: BUILDER=make DISTRO=native LANGUAGE=python2
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: BUILDER=make DISTRO=native LANGUAGE=python3
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: BUILDER=make DISTRO=native LANGUAGE=java
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: BUILDER=make DISTRO=native LANGUAGE=dotnet

    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: clang
      env: BUILDER=make DISTRO=native LANGUAGE=cc
    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: clang
      env: BUILDER=make DISTRO=native LANGUAGE=python2
    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: clang
      env: BUILDER=make DISTRO=native LANGUAGE=python3
    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: clang
      env: BUILDER=make DISTRO=native LANGUAGE=java
    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: clang
      env: BUILDER=make DISTRO=native LANGUAGE=dotnet
# CMake Build Generator
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: BUILDER=cmake DISTRO=native
    - os: linux
      dist: trusty
      language: cpp
      compiler: clang
      env: BUILDER=cmake DISTRO=native

    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: gcc
      env: BUILDER=cmake DISTRO=native
    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: clang
      env: BUILDER=cmake DISTRO=native
# Jobs too long
  allow_failures:
    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: clang
      env: BUILDER=make DISTRO=native LANGUAGE=dotnet

install:
  - ./.travis/install.sh

script:
  - ./.travis/script.sh
>>>>>>> 1292f58e7bf595362b92451962c4c10e27007613
