sudo: required
language: cpp

matrix:
  include:
# Makefile builder
    - os: linux
      dist: trusty
      compiler: gcc
      env: BUILDER=make LANGUAGE=cc
    - os: linux
      dist: trusty
      compiler: gcc
      env: BUILDER=make LANGUAGE=python2
    - os: linux
      dist: trusty
      compiler: gcc
      env: BUILDER=make LANGUAGE=python3
    - os: linux
      dist: trusty
      compiler: gcc
      env: BUILDER=make LANGUAGE=java
    - os: linux
      dist: trusty
      compiler: gcc
      env: BUILDER=make LANGUAGE=dotnet

    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: BUILDER=make LANGUAGE=cc
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: BUILDER=make LANGUAGE=python2
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: BUILDER=make LANGUAGE=python3
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: BUILDER=make LANGUAGE=java
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: BUILDER=make LANGUAGE=dotnet
# CMake Build Generator
    - os: linux
      dist: trusty
      compiler: gcc
      env: BUILDER=cmake
    - os: linux
      dist: trusty
      compiler: clang
      env: BUILDER=cmake

    - os: osx
      osx_image: xcode9.4
      compiler: gcc
      env: BUILDER=cmake
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: BUILDER=cmake
# Jobs too long
  allow_failures:
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: BUILDER=make LANGUAGE=dotnet

install:
  - ./.travis/install.sh

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=`/usr/libexec/java_home -v 1.8`; fi

script:
  - ./.travis/script.sh
